services:
  postgres:
    image: postgres:16-bullseye
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./postgres/db-entrypoint:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - postgres-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: price_analysis_img:dev
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    env_file:
      - .env
    networks:
      - postgres-network


volumes:
  local_postgres_data:


networks:
  postgres-network:
    driver: bridge
